---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 812427107401768960-iRNCgQOaZqWLmJzfSoSnnrolyn1MDcJ
:access_token_secret: ZS4YRnzCUzkwcx6lo0zGgQoz31cUYoql4mI42ADWt5mG8
